import 'server-only';
import {headers} from 'next/headers';
import {z} from 'zod';
import {AppError,database} from './db';
import {getAuth,authObjectId} from './better-auth';
import {digest,verifyPassword,Identity} from './security';
export function checkOrigin(request:Request){const expected=process.env.BETTER_AUTH_URL||process.env.APP_ORIGIN;if(!expected)throw new AppError(503,'Authentication URL is not configured.');const allowed=[new URL(expected).origin,...(process.env.NODE_ENV==='production'?[]:['http://localhost:3000','http://127.0.0.1:3000'])];if(!allowed.includes(request.headers.get('origin')||''))throw new AppError(403,'Request origin is not allowed.');}
export async function jsonBody(request:Request){const length=Number(request.headers.get('content-length')||0);if(length>8192)throw new AppError(413,'Request is too large.');const raw=await request.text();if(raw.length>8192)throw new AppError(413,'Request is too large.');try{return JSON.parse(raw);}catch{throw new AppError(400,'Invalid JSON.');}}
export async function forwardAuth(request:Request,path:string){try{checkOrigin(request);const auth=await getAuth();const url=new URL(request.url);url.pathname='/api/auth/'+path;return auth.handler(new Request(url,{method:request.method,headers:request.headers,body:JSON.stringify(await jsonBody(request))}));}catch(e){return endpoint(async()=>{throw e;});}}
export async function requireIdentity():Promise<Identity>{const requestHeaders=await headers();if(!requestHeaders.get('cookie'))throw new AppError(401,'Login required.');const value=await (await getAuth()).api.getSession({headers:requestHeaders});if(!value)throw new AppError(401,'Session expired.');const db=await database(),user=await db.collection<any>('authUsers').findOne({_id:authObjectId(value.user.id),verified:true,disabled:false});if(!user?.tenantId)throw new AppError(403,'Account approval required.');const tenant=await db.collection<any>('tenants').findOne({_id:user.tenantId,verified:true,disabled:false});if(!tenant)throw new AppError(403,'Company approval required.');const session=await db.collection<any>('authSessions').findOne({_id:authObjectId(value.session.id),userId:authObjectId(value.user.id),expiresAt:{$gt:new Date()}});if(!session)throw new AppError(401,'Session expired.');return {userId:value.user.id,tenantId:user.tenantId,sessionId:value.session.id,profitUntil:session.profitUntil};}
export async function profile(){const identity=await requireIdentity(),db=await database();const [user,tenant]=await Promise.all([db.collection<any>('authUsers').findOne({_id:authObjectId(identity.userId)},{projection:{name:1,email:1}}),db.collection<any>('tenants').findOne({_id:identity.tenantId},{projection:{companyName:1}})]);return {user:{name:user?.name,email:user?.email},company:{name:tenant?.companyName},profitUnlocked:!!identity.profitUntil&&identity.profitUntil>new Date(),businessDataMode:'demo-only'};}
export async function unlockProfit(value:unknown){const identity=await requireIdentity();const input=z.object({password:z.string().min(1).max(128)}).strict().parse(value);const db=await database(),bucket=Math.floor(Date.now()/900000);const attempt=await db.collection<any>('rateLimits').findOneAndUpdate({_id:digest('profit:'+identity.userId)+':'+bucket},{$inc:{count:1},$setOnInsert:{expiresAt:new Date((bucket+2)*900000)}},{upsert:true,returnDocument:'after'});if(!attempt||attempt.count>5)throw new AppError(429,'Too many attempts. Try again in 15 minutes.');const user=await db.collection<any>('authUsers').findOne({_id:authObjectId(identity.userId),tenantId:identity.tenantId});if(!user?.profitPasswordHash||!await verifyPassword(input.password,user.profitPasswordHash))throw new AppError(403,'Profit password is incorrect.');const until=new Date(Date.now()+600000);await db.collection<any>('authSessions').updateOne({_id:authObjectId(identity.sessionId)},{$set:{profitUntil:until}});return {unlockedUntil:until.toISOString()};}
export async function requireProfit(){const identity=await requireIdentity();if(!identity.profitUntil||identity.profitUntil<=new Date())throw new AppError(403,'Unlock profit access first.');return identity;}
export async function endpoint(action:()=>Promise<unknown>){try{return Response.json(await action(),{headers:{'Cache-Control':'no-store'}});}catch(e){if(e instanceof z.ZodError)return Response.json({error:'Please check the form fields.'},{status:400});const error=e instanceof AppError?e:new AppError(503,'The backend is unavailable. Check database configuration.');return Response.json({error:error.message},{status:error.status,headers:{'Cache-Control':'no-store'}});}}
