import 'server-only';
import path from 'node:path';
import {mkdir,realpath,writeFile,readFile,unlink} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {AppError,database} from './db';
import {Identity,tenantFilter} from './security';
type StoredFile={_id:string;tenantId:string;createdBy:string;key:string;name:string;type:string;size:number;createdAt:Date};
const idPattern=/^[a-f0-9-]{36}$/;
async function root(){if(process.env.VERCEL)throw new AppError(503,'Local storage requires the VPS runtime. Configure an external storage provider for Vercel.');const configured=process.env.PRIVATE_STORAGE_ROOT;if(!configured||!path.isAbsolute(configured))throw new AppError(503,'Configure an absolute PRIVATE_STORAGE_ROOT outside the application directory.');const resolved=path.resolve(configured),app=path.resolve(process.cwd());if(resolved===app||resolved.startsWith(app+path.sep))throw new AppError(503,'Private files must be outside the application and public directories.');await mkdir(resolved,{recursive:true,mode:0o700});return realpath(resolved);}
async function tenantDirectory(tenantId:string){if(!idPattern.test(tenantId))throw new AppError(403,'Invalid tenant.');const base=await root(),dir=path.join(base,tenantId);await mkdir(dir,{recursive:true,mode:0o700});const canonical=await realpath(dir);if(!canonical.startsWith(base+path.sep))throw new AppError(403,'Invalid storage location.');return canonical;}
function identify(bytes:Uint8Array){if(bytes.length>=5&&Buffer.from(bytes.subarray(0,5)).toString()==='%PDF-')return {type:'application/pdf',ext:'.pdf'};if(bytes.length>=8&&Buffer.from(bytes.subarray(0,8)).equals(Buffer.from([137,80,78,71,13,10,26,10])))return {type:'image/png',ext:'.png'};if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)return {type:'image/jpeg',ext:'.jpg'};throw new AppError(400,'Only PDF, PNG and JPEG files are accepted.');}
export async function storeFile(identity:Identity,file:File){if(file.size<1||file.size>10*1024*1024)throw new AppError(400,'Files must be between 1 byte and 10 MB.');const bytes=new Uint8Array(await file.arrayBuffer()),format=identify(bytes);const dir=await tenantDirectory(identity.tenantId),id=randomUUID(),key=id+format.ext;const target=path.join(dir,key);await writeFile(target,bytes,{flag:'wx',mode:0o600});const record:StoredFile={_id:id,tenantId:identity.tenantId,createdBy:identity.userId,key,name:file.name.replace(/[\r\n\x00-\x1f]/g,'').slice(0,180)||key,type:format.type,size:bytes.length,createdAt:new Date()};try{await (await database()).collection<StoredFile>('files').insertOne(record);}catch(e){await unlink(target).catch(()=>{});throw e;}return {id:record._id,name:record.name,type:record.type,size:record.size,url:'/api/files/'+record._id};}
export async function getFile(identity:Identity,id:string){if(!idPattern.test(id))throw new AppError(404,'File not found.');const record=await (await database()).collection<StoredFile>('files').findOne(tenantFilter(identity,{_id:id}));if(!record||!new RegExp('^'+id+'\\.(pdf|png|jpg)$').test(record.key))throw new AppError(404,'File not found.');const dir=await tenantDirectory(identity.tenantId);const file=await realpath(path.join(dir,record.key));if(!file.startsWith(dir+path.sep))throw new AppError(403,'Invalid file location.');return {record,bytes:await readFile(file)};}
