import {amountWords} from './amount-words';
import {Bill,State,totals,lineTotal,paid,balance,roundedTotal} from './domain';
import type {InvoiceTemplate} from './extensions';
export const safeFilename=(name:string)=>name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,100)||'document';
const text=(value:unknown)=>String(value??'').replace(/₹/g,'INR ').replace(/[–—]/g,'-').replace(/→/g,'to').replace(/·/g,' / ');
const cash=(n:number)=>'INR '+n.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
export function downloadBytes(name:string,bytes:Uint8Array,mime:string){const url=URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type:mime}));const link=document.createElement('a');link.href=url;link.download=safeFilename(name);link.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
export async function workbookBytes(title:string,headers:string[],rows:(string|number)[][],description=''){
 const {default:ExcelJS}=await import('exceljs');const workbook=new ExcelJS.Workbook();workbook.creator='iTech Computers';const sheet=workbook.addWorksheet('Report');
 sheet.addRow([title]);sheet.addRow([description]);sheet.addRow(headers);rows.forEach(r=>sheet.addRow(r));sheet.views=[{state:'frozen',ySplit:3}];sheet.autoFilter={from:{row:3,column:1},to:{row:3,column:headers.length}};
 sheet.getRow(1).font={bold:true,size:18,color:{argb:'FF5035BE'}};sheet.getRow(3).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(3).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF6246E5'}};
 headers.forEach((h,i)=>{const col=sheet.getColumn(i+1);col.width=Math.min(48,Math.max(15,h.length+3,...rows.slice(0,100).map(r=>String(r[i]??'').length+2)));col.alignment={vertical:'top',wrapText:true};if(/amount|total|value|due|paid|profit|tax|gst|expense|receipt|price|balance/i.test(h))col.numFmt='#,##0.00';});
 sheet.pageSetup={paperSize:9,orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0};return new Uint8Array(await workbook.xlsx.writeBuffer());
}
export async function reportPdfBytes(title:string,headers:string[],rows:(string|number)[][],description=''){
 const {jsPDF}=await import('jspdf');const {autoTable}=await import('jspdf-autotable');const doc=new jsPDF({orientation:headers.length>6?'landscape':'portrait'});const width=doc.internal.pageSize.getWidth();
 doc.setFontSize(18);doc.text(text(title),14,19);doc.setFontSize(9);doc.text(doc.splitTextToSize(text(description),width-28),14,27);
 autoTable(doc,{startY:38,head:[headers.map(text)],body:rows.map(r=>r.map(v=>typeof v==='number'?v.toLocaleString('en-IN',{maximumFractionDigits:2}):text(v))),styles:{fontSize:8,cellPadding:3,overflow:'linebreak'},headStyles:{fillColor:[98,70,229]},margin:{top:16,bottom:19}});
 for(let i=1;i<=doc.getNumberOfPages();i++){doc.setPage(i);doc.setFontSize(8);doc.text(`iTech Computers / Demo report / Page ${i} of ${doc.getNumberOfPages()}`,14,doc.internal.pageSize.getHeight()-9);}return new Uint8Array(doc.output('arraybuffer'));
}
export async function invoicePdfBytes(s:State,b:Bill,templateId?:string){
 const t=s.templates.find(t=>t.id===(templateId||b.templateId||s.defaultTemplateId))||s.templates[0];const f=t.fields;const company=b.shopSnapshot||s.settings,customer=b.customerSnapshot||s.customers.find(c=>c.id===b.customerId);const total=totals(b),inter=b.taxMode==='Inter-state';const {jsPDF}=await import('jspdf');const {autoTable}=await import('jspdf-autotable');const doc=new jsPDF({orientation:t.orientation,format:t.paper.toLowerCase() as 'a4'|'letter'});const width=doc.internal.pageSize.getWidth();let y=14;
 const colour:[number,number,number]=[1,3,5].map(i=>parseInt(t.accent.slice(i,i+2),16)||0) as [number,number,number];
 const table=(head:string[]|null,body:(string|number)[][],options:Record<string,unknown>={})=>{autoTable(doc,{startY:y,...(head?{head:[head.map(text)]}:{}),body:body.map(r=>r.map(text)),rowPageBreak:'avoid',theme:t.borders?'grid':t.striped?'striped':'plain',styles:{fontSize:t.fontSize*0.75,cellPadding:1.5,overflow:'linebreak'},headStyles:{fillColor:colour,textColor:255},margin:{left:12,right:12,top:14,bottom:20},...options});y=(doc as typeof doc&{lastAutoTable:{finalY:number}}).lastAutoTable.finalY+2;};
 doc.setFontSize(16);doc.setTextColor(...colour);doc.text(text(t.title||(b.kind==='Quotation'?'Quotation':b.kind==='Service'?'Service Invoice':total.tax?'Tax Invoice':'Sales Invoice')),width/2,y,{align:'center'});y+=8;doc.setTextColor(20);
 if(f.logo&&company.logo){try{const response=await fetch(company.logo);if(!response.ok)throw new Error('Logo unavailable');const bytes=new Uint8Array(await response.arrayBuffer());const x=t.logoPosition==='right'?width-37:t.logoPosition==='center'?width/2-12:12;doc.addImage(bytes,'PNG',x,y,24,16,undefined,'FAST');y+=20;}catch{/* Unavailable session logos must not prevent invoice download. */}}
 const companyText=[f.shopName&&company.name,f.shopAddress&&company.address,f.shopGst&&'GSTIN: '+company.gst,f.shopPhone&&company.phone,f.shopEmail&&company.email].filter(Boolean).join('\n');
 const meta=[f.number&&'Document: '+b.id,f.date&&'Date: '+b.date,f.due&&'Due / valid until: '+b.due,f.reference&&'Reference: '+(b.jobId||b.sourceId||''),f.order&&'Buyer order: '+(b.orderRef||''),f.delivery&&'Delivery note: '+(b.deliveryNote||''),f.dispatch&&'Dispatch: '+(b.dispatch||''),f.destination&&'Place of supply: '+(b.placeOfSupply||'Tamil Nadu')].filter(Boolean).join('\n');table(null,[[companyText,meta]],{columnStyles:{0:{cellWidth:(width-24)/2},1:{cellWidth:(width-24)/2}}});
 const buyer=['Buyer (Bill to)',f.customerName&&customer?.name,f.customerAddress&&customer?.address,f.customerPhone&&customer?.phone,f.customerGst&&'GSTIN: '+(customer?.gst||'Not provided')].filter(Boolean).join('\n');const ship=b.shipTo;table(null,[[buyer,...(f.shipping?[['Ship to (Deliver to)',ship?.name||customer?.name,ship?.address||customer?.address,ship?.phone||customer?.phone,ship?.state,ship?.postalCode].filter(Boolean).join('\n')]:[])]]);
 const columns=t.columns.filter(c=>c.show);const itemRows=b.lines.map((l,i)=>{const tax=lineTotal(l,b.inclusive,b.taxMode);const cells:Record<string,string|number>={index:i+1,description:[l.name,f.serials&&l.serials.join(', '),f.model&&s.products.find(p=>p.id===l.productId)?.model,f.warranty&&l.warranty>0&&'Warranty: '+l.warranty+' months'].filter(Boolean).join('\n'),hsn:l.hsn,tax:l.taxTreatment==='Exempt'?'Exempt':l.taxTreatment==='NonGST'?'Non-GST':l.tax+'%',qty:l.qty,rateIncl:cash(b.inclusive?l.rate:l.rate*(1+l.tax/100)),rateExcl:cash(b.inclusive?l.rate/(1+l.tax/100):l.rate),discount:l.discountType==='Amount'?cash(l.discount):l.discount+'%',warranty:l.warranty+' months',amount:cash(tax.base)};return columns.map(c=>cells[c.id]??'');});table(columns.map(c=>c.label),itemRows,{styles:{fontSize:Math.min(t.fontSize*0.75,9),cellPadding:1.5,overflow:'linebreak'},columnStyles:Object.fromEntries(columns.map((c,i)=>[i,{halign:c.align}]))});
 const summary:(string|number)[][]=[];if(f.subtotal)summary.push(['Taxable value',cash(total.base)]);if(f.taxes)summary.push(...(inter?[['IGST',cash(total.igst)]]:[['CGST',cash(total.cgst)],['SGST',cash(total.sgst)]]));if(f.grandTotal)summary.push(['Total',cash(roundedTotal(b))]);if(f.payments&&b.kind!=='Quotation')summary.push(['Received',cash(b.previewPaid??paid(s,b.id))],['Balance due',cash(b.previewPaid!==undefined?Math.max(0,roundedTotal(b)-b.previewPaid):balance(s,b))]);if(summary.length)table(null,summary,{columnStyles:{0:{fontStyle:'bold'},1:{halign:'right'}}});
 if(f.amountWords)table(null,[['Amount in words',amountWords(roundedTotal(b))]]);
 if(f.taxSummary){const groups=new Map<string,{hsn:string;rate:number;base:number;cgst:number;sgst:number;igst:number;treatment?:string}>();b.lines.forEach(l=>{const treatment=l.taxTreatment||'Taxable';const key=treatment+'-'+l.hsn+'-'+l.tax;const v=lineTotal(l,b.inclusive,b.taxMode);const row=groups.get(key)||{hsn:l.hsn,rate:(treatment==='Exempt'||treatment==='NonGST')?0:l.tax,base:0,cgst:0,sgst:0,igst:0,treatment};row.base+=v.base;row.cgst+=v.cgst;row.sgst+=v.sgst;row.igst+=v.igst;groups.set(key,row);});table(inter?['HSN / SAC','Rate','Taxable','IGST']:['HSN / SAC','GST rate','Taxable','CGST','SGST'],[...groups.values()].map(x=>[x.hsn,x.treatment==='Exempt'?'Exempt':x.treatment==='NonGST'?'Non-GST':x.rate+'%',cash(x.base),...(inter?[cash(x.igst)]:[cash(x.cgst),cash(x.sgst)])]));}
 if(f.notes&&b.notes)table(null,[['Notes',b.notes]]);if(f.declaration)table(null,[['Declaration',company.declaration]]);if(f.bank)table(null,[['Bank details',[company.name,company.bank,company.account,company.ifsc].join('\n')]]);if(f.signatures)table(null,[['Customer seal and signature','For '+company.name+'\n\nAuthorised signatory']]);
 for(let i=1;i<=doc.getNumberOfPages();i++){doc.setPage(i);doc.setFontSize(8);doc.setTextColor(70);doc.text(text((f.footer?t.footer+' / ':'')+'DEMO - not a valid tax invoice'),12,doc.internal.pageSize.getHeight()-12,{maxWidth:width-24});doc.text(`${b.id} / ${i} of ${doc.getNumberOfPages()}`,12,doc.internal.pageSize.getHeight()-7);}return new Uint8Array(doc.output('arraybuffer'));
}
export async function invoiceZipBytes(s:State,bills:Bill[],templateId?:string){if(!bills.length)throw new Error('Select at least one invoice.');if(bills.length>100)throw new Error('Export up to 100 invoices at a time in this prototype.');const {default:JSZip}=await import('jszip');const zip=new JSZip();for(const b of bills){zip.file(safeFilename(b.id)+'.pdf',await invoicePdfBytes(s,b,templateId));}zip.file('invoice-index.xlsx',await workbookBytes('Invoice archive',['Invoice','Date','Customer','Total','Paid','Due'],bills.map(b=>[b.id,b.date,s.customers.find(c=>c.id===b.customerId)?.name||'',roundedTotal(b),paid(s,b.id),balance(s,b)]),'Selected records / Demo workspace'));return zip.generateAsync({type:'uint8array',compression:'DEFLATE'});}
